### ISSUE TITLE
No user feedback given while pulling Thread

### ISSUE THREAD

**Issue by pwdelbloomboard** [kbravh/tweet-to-markdown#13]
This is more of a usability request rather than a bug.

Basically, when you call a long thread with the -t flag, ttm sits there, presumably doing work, but not giving any user feedback.

So a quick way to perhaps, "workaround," this problem might be to add to the documentation and instruct users how to check whether a PID is running, just open up a new tab and check, ```ps``` and you should see that the process is still ongoing.

Another solution would maybe to allow the user to enable logging output with perhaps an ```-l``` flag.

Of course a more universal user-centric approach might be to add something like a progress bar, or a spinning, "working," icon.

Progress bar - perhaps more technically difficult for this tool, because you can't necessarily predict the total size of a Tweet thread at the start, I am not sure.

https://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script

Spinning ball - at least shows the user that a process is still in operation, if not predicting when it might be done.

https://stackoverflow.com/questions/10470139/creating-rotating-circle-using-characters-in-shell-script

**Comment by kbravh** [comment]
@pwdelbloomboard Great suggestion; I've just pushed out a new version (2.2.0) with a small counter to show the progress of tweet thread downloads.
