### ISSUE TITLE
Will this tool still work under Twitter new API policy?

### ISSUE THREAD

**Issue by cangyuyao** [kbravh/tweet-to-markdown#20]
Free access will stop from Feb-9.

**Comment by kbravh** [comment]
@cangyuyao I hope to be able to continue supporting this library and my API key service. However, Twitter still has not published any pricing yet. I'll be able to provide a more substantial update once they do 👍

**Comment by kbravh** [comment]
Hi @cangyuyao, unfortunately I will not be able to continue offering the TTM free API keys with the Twitter changes. If you have your own bearer token from Twitter itself, you can use that, but using a key from https://ttm.kbravh.dev will stop working on Feb. 13.
